# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppPSO <- function(LOOPID, ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, IF_PARALLEL, VERBOSE) {
    .Call('DiscrimOD_cppPSO', PACKAGE = 'DiscrimOD', LOOPID, ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, IF_PARALLEL, VERBOSE)
}

cppDesignCriterion <- function(ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, DESIGN) {
    .Call('DiscrimOD_cppDesignCriterion', PACKAGE = 'DiscrimOD', ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, DESIGN)
}

cppEquivalence <- function(ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, GBEST_VAL, PARA_SET, alpha, env, nGrid) {
    .Call('DiscrimOD_cppEquivalence', PACKAGE = 'DiscrimOD', ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, GBEST_VAL, PARA_SET, alpha, env, nGrid)
}

