# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Distance measurement function for the T-optiaml criterion
#'
#' @param xt vector of design points.
#' @param xr vector of design weight. Its length must be equal to the length of \code{x} and \code{sum(w)} should be 1.
#' @return Fisher information matrix.
#' @references Dette, H., Kiss, C., Bevanda, M., & Bretz, F. (2010). Optimal designs for the EMAX, log-linear and exponential models. Biometrika, 97(2), 513-518.
#' @details
#' 
#' @export
T_optimal <- function(xt, xr) {
    .Call('DiscrimOD_T_optimal', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_normal_hetero <- function(xt, xr) {
    .Call('DiscrimOD_KL_normal_hetero', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_logistic <- function(xt, xr) {
    .Call('DiscrimOD_KL_logistic', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_lognormal_a <- function(xt, xr) {
    .Call('DiscrimOD_KL_lognormal_a', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_lognormal_b <- function(xt, xr) {
    .Call('DiscrimOD_KL_lognormal_b', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_lognormal_c <- function(xt, xr) {
    .Call('DiscrimOD_KL_lognormal_c', PACKAGE = 'DiscrimOD', xt, xr)
}

#' @export
KL_gamma_b <- function(xt, xr) {
    .Call('DiscrimOD_KL_gamma_b', PACKAGE = 'DiscrimOD', xt, xr)
}

cppPSO <- function(LOOPID, ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, IF_PARALLEL, VERBOSE) {
    .Call('DiscrimOD_cppPSO', PACKAGE = 'DiscrimOD', LOOPID, ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, IF_PARALLEL, VERBOSE)
}

cppDesignCriterion <- function(ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, DESIGN) {
    .Call('DiscrimOD_cppDesignCriterion', PACKAGE = 'DiscrimOD', ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, FIXEDVALUE, env, DESIGN)
}

cppEquivalence <- function(ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, GBEST_VAL, PARA_SET, alpha, env, nGrid) {
    .Call('DiscrimOD_cppEquivalence', PACKAGE = 'DiscrimOD', ALG_INFO_LIST, OBJ_INFO_LIST, MODEL_INFO_LIST, GBEST_VAL, PARA_SET, alpha, env, nGrid)
}

